name: metabarcoding_env
channels:
  - conda 
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
 - python=3.10.15
 - r-base=4.3.3
 - r-tidyverse=2.0.0
 - r-ape=5.8
 - r-argparse=2.2.3
 - r-patchwork=1.3.0
 - r-magrittr=2.0.3
 - bioconductor-dada2=1.30.0
 - bioconductor-shortread=1.60.0
 - bioconductor-biostrings=2.70.1
 - bioconductor-decipher=2.30.0
 - bioconductor-phyloseq=1.46.0
 - cutadapt=4.6=py310h4b81fae_1
 - blast=2.16.0
 - fasttree=2.1.11
 - git=2.47.1